export const getFlagPng = (slug: string) => {
    switch (slug) {
        case 'alabama':
            return require('../../assets/images/all-flags-png/alabama.png');
        case 'alaska':
            return require('../../assets/images/all-flags-png/alaska.png');
        case 'arizona':
            return require('../../assets/images/all-flags-png/arizona.png');
        case 'arkansas':
            return require('../../assets/images/all-flags-png/arkansas.png');
        case 'california':
            return require('../../assets/images/all-flags-png/california.png');
        case 'colorado':
            return require('../../assets/images/all-flags-png/colorado.png');
        case 'connecticut':
            return require('../../assets/images/all-flags-png/connecticut.png');
        case 'delaware':
            return require('../../assets/images/all-flags-png/delaware.png');
        case 'district-of-columbia':
            return require('../../assets/images/all-flags-png/district-of-columbia.png');
        case 'florida':
            return require('../../assets/images/all-flags-png/florida.png');
        case 'georgia':
            return require('../../assets/images/all-flags-png/georgia.png');
        case 'hawaii':
            return require('../../assets/images/all-flags-png/hawaii.png');
        case 'idaho':
            return require('../../assets/images/all-flags-png/idaho.png');
        case 'illinois':
            return require('../../assets/images/all-flags-png/illinois.png');
        case 'indiana':
            return require('../../assets/images/all-flags-png/indiana.png');
        case 'iowa':
            return require('../../assets/images/all-flags-png/iowa.png');
        case 'kansas':
            return require('../../assets/images/all-flags-png/kansas.png');
        case 'kentucky':
            return require('../../assets/images/all-flags-png/kentucky.png');
        case 'louisiana':
            return require('../../assets/images/all-flags-png/louisiana.png');
        case 'maine':
            return require('../../assets/images/all-flags-png/maine.png');
        case 'maryland':
            return require('../../assets/images/all-flags-png/maryland.png');
        case 'massachusetts':
            return require('../../assets/images/all-flags-png/massachusetts.png');
        case 'michigan':
            return require('../../assets/images/all-flags-png/michigan.png');
        case 'minnesota':
            return require('../../assets/images/all-flags-png/minnesota.png');
        case 'mississippi':
            return require('../../assets/images/all-flags-png/mississippi.png');
        case 'missouri':
            return require('../../assets/images/all-flags-png/missouri.png');
        case 'montana':
            return require('../../assets/images/all-flags-png/montana.png');
        case 'nebraska':
            return require('../../assets/images/all-flags-png/nebraska.png');
        case 'nevada':
            return require('../../assets/images/all-flags-png/nevada.png');
        case 'new-hampshire':
            return require('../../assets/images/all-flags-png/new-hampshire.png');
        case 'new-jersey':
            return require('../../assets/images/all-flags-png/new-jersey.png');
        case 'new-mexico':
            return require('../../assets/images/all-flags-png/new-mexico.png');
        case 'new-york':
            return require('../../assets/images/all-flags-png/new-york.png');
        case 'north-carolina':
            return require('../../assets/images/all-flags-png/north-carolina.png');
        case 'north-dakota':
            return require('../../assets/images/all-flags-png/north-dakota.png');
        case 'ohio':
            return require('../../assets/images/all-flags-png/ohio.png');
        case 'oklahoma':
            return require('../../assets/images/all-flags-png/oklahoma.png');
        case 'oregon':
            return require('../../assets/images/all-flags-png/oregon.png');
        case 'pennsylvania':
            return require('../../assets/images/all-flags-png/pennsylvania.png');
        case 'rhode-island':
            return require('../../assets/images/all-flags-png/rhode-island.png');
        case 'south-carolina':
            return require('../../assets/images/all-flags-png/south-carolina.png');
        case 'south-dakota':
            return require('../../assets/images/all-flags-png/south-dakota.png');
        case 'tennessee':
            return require('../../assets/images/all-flags-png/tennessee.png');
        case 'texas':
            return require('../../assets/images/all-flags-png/texas.png');
        case 'utah':
            return require('../../assets/images/all-flags-png/utah.png');
        case 'vermont':
            return require('../../assets/images/all-flags-png/vermont.png');
        case 'virginia':
            return require('../../assets/images/all-flags-png/virginia.png');
        case 'washington':
            return require('../../assets/images/all-flags-png/washington.png');
        case 'west-virginia':
            return require('../../assets/images/all-flags-png/west-virginia.png');
        case 'wisconsin':
            return require('../../assets/images/all-flags-png/wisconsin.png');
        case 'wyoming':
            return require('../../assets/images/all-flags-png/wyoming.png');
        case 'puerto-rico':
            return require('../../assets/images/all-flags-png/puerto-rico.png');
        default:
            return null;
    }
};
