export const getFlagSvg = (slug: string) => {
    switch (slug) {
      case 'alabama':
        return require('../../assets/images/all-flags/alabama.svg').default;
      case 'alaska':
        return require('../../assets/images/all-flags/alaska.svg').default;
      case 'arizona':
        return require('../../assets/images/all-flags/arizona.svg').default;
      case 'arkansas':
        return require('../../assets/images/all-flags/arkansas.svg').default;
      case 'california':
        return require('../../assets/images/all-flags/california.svg').default;
      case 'colorado':
        return require('../../assets/images/all-flags/colorado.svg').default;
      case 'connecticut':
        return require('../../assets/images/all-flags/connecticut.svg').default;
      case 'delaware':
        return require('../../assets/images/all-flags/delaware.svg').default;
      case 'florida':
        return require('../../assets/images/all-flags/florida.svg').default;
      case 'georgia':
        return require('../../assets/images/all-flags/georgia.svg').default;
      case 'hawaii':
        return require('../../assets/images/all-flags/hawaii.svg').default;
      case 'idaho':
        return require('../../assets/images/all-flags/idaho.svg').default;
      case 'illinois':
        return require('../../assets/images/all-flags/illinois.svg').default;
      case 'indiana':
        return require('../../assets/images/all-flags/indiana.svg').default;
      case 'iowa':
        return require('../../assets/images/all-flags/iowa.svg').default;
      case 'kansas':
        return require('../../assets/images/all-flags/kansas.svg').default;
      case 'kentucky':
        return require('../../assets/images/all-flags/kentucky.svg').default;
      case 'louisiana':
        return require('../../assets/images/all-flags/louisiana.svg').default;
      case 'maine':
        return require('../../assets/images/all-flags/maine.svg').default;
      case 'maryland':
        return require('../../assets/images/all-flags/maryland.svg').default;
      case 'massachusetts':
        return require('../../assets/images/all-flags/massachusetts.svg').default;
      case 'michigan':
        return require('../../assets/images/all-flags/michigan.svg').default;
      case 'minnesota':
        return require('../../assets/images/all-flags/minnesota.svg').default;
      case 'mississippi':
        return require('../../assets/images/all-flags/mississippi.svg').default;
      case 'missouri':
        return require('../../assets/images/all-flags/missouri.svg').default;
      case 'montana':
        return require('../../assets/images/all-flags/montana.svg').default;
      case 'nebraska':
        return require('../../assets/images/all-flags/nebraska.svg').default;
      case 'nevada':
        return require('../../assets/images/all-flags/nevada.svg').default;
      case 'new-hampshire':
        return require('../../assets/images/all-flags/new-hampshire.svg').default;
      case 'new-jersey':
        return require('../../assets/images/all-flags/new-jersey.svg').default;
      case 'new-mexico':
        return require('../../assets/images/all-flags/new-mexico.svg').default;
      case 'new-york':
        return require('../../assets/images/all-flags/new-york.svg').default;
      case 'north-carolina':
        return require('../../assets/images/all-flags/north-carolina.svg').default;
      case 'north-dakota':
        return require('../../assets/images/all-flags/north-dakota.svg').default;
      case 'ohio':
        return require('../../assets/images/all-flags/ohio.svg').default;
      case 'oklahoma':
        return require('../../assets/images/all-flags/oklahoma.svg').default;
      case 'oregon':
        return require('../../assets/images/all-flags/oregon.svg').default;
      case 'pennsylvania':
        return require('../../assets/images/all-flags/pennsylvania.svg').default;
      case 'rhode-island':
        return require('../../assets/images/all-flags/rhode-island.svg').default;
      case 'south-carolina':
        return require('../../assets/images/all-flags/south-carolina.svg').default;
      case 'south-dakota':
        return require('../../assets/images/all-flags/south-dakota.svg').default;
      case 'tennessee':
        return require('../../assets/images/all-flags/tennessee.svg').default;
      case 'texas':
        return require('../../assets/images/all-flags/texas.svg').default;
      case 'utah':
        return require('../../assets/images/all-flags/utah.svg').default;
      case 'vermont':
        return require('../../assets/images/all-flags/vermont.svg').default;
      case 'virginia':
        return require('../../assets/images/all-flags/virginia.svg').default;
      case 'washington':
        return require('../../assets/images/all-flags/washington.svg').default;
      case 'west-virginia':
        return require('../../assets/images/all-flags/west-virginia.svg').default;
      case 'wisconsin':
        return require('../../assets/images/all-flags/wisconsin.svg').default;
      case 'wyoming':
        return require('../../assets/images/all-flags/wyoming.svg').default;
      default:
        return null;
    }
  };
  